name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore "TodoApp.api/TodoApp.api.csproj"

    - name: Build
      run: dotnet build --no-restore "TodoApp.api/TodoApp.api.csproj" -c Release

    - name: Test
      run: dotnet test --no-build "TodoApp.api/TodoApp.api.csproj" --verbosity normal

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t sudeopan/todoapp-backend:latest .

    - name: Push Docker image
      run: docker push sudeopan/todoapp-backend:latest
